#!/usr/bin/env bash
# xcind-proxy-lib.bash — Proxy hooks and shared lifecycle functions
#
# Provides two hooks:
#   xcind-proxy-hook (GENERATE) — generates Traefik proxy configuration
#   __xcind-proxy-execute-hook (EXECUTE) — ensures proxy is running
#
# Also provides __xcind-proxy-ensure-* functions used by both the hooks
# and the xcind-proxy CLI to manage proxy infrastructure.
#
# This file is auto-sourced by xcind-lib.bash. Hooks are registered by
# default — apps only need to declare XCIND_PROXY_EXPORTS to use them.

# --------------------------------------------------------------------------
# Shared Constants
# --------------------------------------------------------------------------

XCIND_PROXY_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/xcind/proxy"
XCIND_PROXY_STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/xcind/proxy"
XCIND_PROXY_COMPOSE="${XCIND_PROXY_STATE_DIR}/compose.yaml"
XCIND_PROXY_NETWORK="xcind-proxy"
# Backward compat alias for messages and hook references
# shellcheck disable=SC2034 # Used externally by tests and CLI
XCIND_PROXY_DIR="$XCIND_PROXY_CONFIG_DIR"

# --------------------------------------------------------------------------
# Proxy Lifecycle Functions
# --------------------------------------------------------------------------

# Ensure the xcind-proxy Docker network exists.
__xcind-proxy-ensure-network() {
  if docker network inspect "$XCIND_PROXY_NETWORK" &>/dev/null; then
    return 0
  fi

  if ! docker network create "$XCIND_PROXY_NETWORK" >/dev/null; then
    echo "Error: Failed to create Docker network '$XCIND_PROXY_NETWORK'." >&2
    echo "Check that Docker is running and you have permission to create networks." >&2
    return 1
  fi
}

# Serialize a value as a double-quoted Bash string literal, escaping
# backslash, double-quote, dollar, and backtick so the resulting
# assignment is safe to source without executing embedded shell syntax.
# Bash 3.2+ compatible — no external tools required.
__xcind-proxy-quote-value() {
  local val="$1"
  val="${val//\\/\\\\}" # backslash → \\
  val="${val//\"/\\\"}" # double-quote → \"
  val="${val//\$/\\\$}" # dollar → \$
  val="${val//\`/\\\`}" # backtick → \`
  printf '"%s"' "$val"
}

# Write (or overwrite) config.sh with the current XCIND_PROXY_* values.
# Each value is serialized via __xcind-proxy-quote-value so that
# double-quotes, dollar signs, backticks, and backslashes in CLI-supplied
# values do not corrupt the sourceable file or execute shell code on
# next source. Writes to a process-unique mktemp sidecar and renames into
# place atomically; removes the sidecar on mv failure.
# Callers must set the variables before calling this function.
__xcind-proxy-write-config() {
  local tmp
  tmp=$(mktemp "${XCIND_PROXY_CONFIG_DIR}/config.sh.XXXXXX") || return 1
  local q_domain q_image q_http_port q_dashboard q_dashboard_port
  local q_tls_mode q_https_port q_tls_cert q_tls_key
  q_domain=$(__xcind-proxy-quote-value "${XCIND_PROXY_DOMAIN:-localhost}")
  q_image=$(__xcind-proxy-quote-value "${XCIND_PROXY_IMAGE:-traefik:v3}")
  q_http_port=$(__xcind-proxy-quote-value "${XCIND_PROXY_HTTP_PORT:-80}")
  q_dashboard=$(__xcind-proxy-quote-value "${XCIND_PROXY_DASHBOARD:-false}")
  q_dashboard_port=$(__xcind-proxy-quote-value "${XCIND_PROXY_DASHBOARD_PORT:-8080}")
  q_tls_mode=$(__xcind-proxy-quote-value "${XCIND_PROXY_TLS_MODE:-auto}")
  q_https_port=$(__xcind-proxy-quote-value "${XCIND_PROXY_HTTPS_PORT:-443}")
  q_tls_cert=$(__xcind-proxy-quote-value "${XCIND_PROXY_TLS_CERT_FILE:-}")
  q_tls_key=$(__xcind-proxy-quote-value "${XCIND_PROXY_TLS_KEY_FILE:-}")
  cat >"$tmp" <<EOF
# xcind-proxy global configuration
# This file is regenerated by \`xcind-proxy init\` when flags are passed.

# Domain suffix for generated hostnames (.localhost = zero DNS config, RFC 6761)
XCIND_PROXY_DOMAIN=${q_domain}

# Traefik Docker image
XCIND_PROXY_IMAGE=${q_image}

# Host port for HTTP traffic
XCIND_PROXY_HTTP_PORT=${q_http_port}

# Enable Traefik dashboard
XCIND_PROXY_DASHBOARD=${q_dashboard}

# Dashboard port (only used if dashboard is enabled)
XCIND_PROXY_DASHBOARD_PORT=${q_dashboard_port}

# TLS mode: auto | custom | disabled
#   auto     — mkcert wildcard for \$XCIND_PROXY_DOMAIN if mkcert is available;
#              otherwise a self-signed wildcard generated via openssl.
#   custom   — use XCIND_PROXY_TLS_CERT_FILE / XCIND_PROXY_TLS_KEY_FILE.
#   disabled — HTTP-only, no :443 entrypoint, no certs.
XCIND_PROXY_TLS_MODE=${q_tls_mode}

# Host port for HTTPS traffic (ignored when TLS is disabled)
XCIND_PROXY_HTTPS_PORT=${q_https_port}

# Custom TLS cert/key (absolute paths) — only used when TLS mode = custom
XCIND_PROXY_TLS_CERT_FILE=${q_tls_cert}
XCIND_PROXY_TLS_KEY_FILE=${q_tls_key}
EOF
  if ! mv -- "$tmp" "${XCIND_PROXY_CONFIG_DIR}/config.sh"; then
    rm -f -- "$tmp"
    return 1
  fi
}

# Ensure proxy infrastructure files exist.
# Creates config.sh (if missing) in XCIND_PROXY_CONFIG_DIR,
# compose.yaml and traefik.yaml in XCIND_PROXY_STATE_DIR.
# Note: xcind-proxy init may regenerate config.sh explicitly via
# __xcind-proxy-write-config when CLI flags are passed.
# Calls __xcind-proxy-ensure-network after generating files.
__xcind-proxy-ensure-init() {
  mkdir -p "$XCIND_PROXY_CONFIG_DIR" "$XCIND_PROXY_STATE_DIR"

  # Write config.sh only if it doesn't exist (preserves user edits)
  if [ ! -f "$XCIND_PROXY_CONFIG_DIR/config.sh" ]; then
    __xcind-proxy-write-config
  fi

  # Source config for variable expansion
  # shellcheck disable=SC1091
  source "$XCIND_PROXY_CONFIG_DIR/config.sh"

  local tls_mode="${XCIND_PROXY_TLS_MODE:-auto}"
  local tls_enabled=true
  [[ $tls_mode == "disabled" ]] && tls_enabled=false

  # Dashboard bits (orthogonal to TLS)
  local dashboard_command=""
  local dashboard_port=""
  if [ "${XCIND_PROXY_DASHBOARD:-false}" = "true" ]; then
    dashboard_command='
      - "--api.dashboard=true"'
    dashboard_port="
      - \"${XCIND_PROXY_DASHBOARD_PORT:-8080}:8080\""
  fi

  # TLS-conditional compose fragments
  local https_port_line=""
  local cert_volume_line=""
  local dynamic_volume_line=""
  if [[ $tls_enabled == true ]]; then
    https_port_line="
      - \"${XCIND_PROXY_HTTPS_PORT:-443}:443\""
    cert_volume_line="
      - ./certs:/etc/traefik/certs:ro"
    dynamic_volume_line="
      - ./dynamic:/etc/traefik/dynamic:ro"
  fi

  cat >"$XCIND_PROXY_COMPOSE" <<EOF
name: xcind-proxy

services:
  traefik:
    image: ${XCIND_PROXY_IMAGE:-traefik:v3}
    command:
      - "--configFile=/etc/traefik/traefik.yaml"${dashboard_command}
    ports:
      - "${XCIND_PROXY_HTTP_PORT:-80}:80"${https_port_line}${dashboard_port}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro${dynamic_volume_line}${cert_volume_line}
    networks:
      - xcind-proxy
    restart: unless-stopped
    labels:
      - "xcind.managed=true"
      - "xcind.component=proxy"

networks:
  xcind-proxy:
    external: true
EOF

  # Write traefik.yaml (always regenerated)
  local dashboard_config=""
  if [ "${XCIND_PROXY_DASHBOARD:-false}" = "true" ]; then
    dashboard_config="
api:
  dashboard: true
  insecure: true"
  fi

  # TLS-conditional traefik.yaml fragments
  local websecure_entry=""
  local file_provider=""
  if [[ $tls_enabled == true ]]; then
    websecure_entry='
  websecure:
    address: ":443"'
    file_provider="
  file:
    directory: /etc/traefik/dynamic
    watch: true"
  fi

  cat >"$XCIND_PROXY_STATE_DIR/traefik.yaml" <<EOF
entryPoints:
  web:
    address: ":80"${websecure_entry}

providers:
  docker:
    exposedByDefault: false
    network: xcind-proxy${file_provider}

log:
  level: INFO${dashboard_config}
EOF

  # Dynamic TLS config (only when TLS is enabled)
  local dynamic_dir="$XCIND_PROXY_STATE_DIR/dynamic"
  if [[ $tls_enabled == true ]]; then
    mkdir -p "$dynamic_dir"
    cat >"$dynamic_dir/tls.yaml" <<'EOF'
# AUTO-GENERATED by xcind-proxy. Regenerated on each init/up.
tls:
  certificates:
    - certFile: /etc/traefik/certs/wildcard.crt
      keyFile: /etc/traefik/certs/wildcard.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/wildcard.crt
        keyFile: /etc/traefik/certs/wildcard.key
EOF
    # Ensure the certs directory exists so the bind mount doesn't fail
    # even when cert provisioning is deferred to __xcind-proxy-ensure-certs.
    mkdir -p "$XCIND_PROXY_STATE_DIR/certs"
  else
    # TLS disabled: remove any stale dynamic/ tls config to keep Traefik happy.
    rm -f "$dynamic_dir/tls.yaml"
  fi

  # Migration: remove generated files from old locations.
  # - Config dir: the previous config-dir → state-dir migration.
  # - State dir/docker-compose.yaml: the previous docker-compose.yaml →
  #   compose.yaml rename (Compose Specification v1.28+ convention).
  rm -f \
    "$XCIND_PROXY_CONFIG_DIR/docker-compose.yaml" \
    "$XCIND_PROXY_CONFIG_DIR/traefik.yaml" \
    "$XCIND_PROXY_STATE_DIR/docker-compose.yaml"

  # Create Docker network if it doesn't exist
  __xcind-proxy-ensure-network
}

# Provision the wildcard TLS certificate used by Traefik when TLS is enabled.
# Writes $XCIND_PROXY_STATE_DIR/certs/wildcard.{crt,key} and a sibling
# "domain" marker file recording the domain the cert was minted for.
#
# Resolution order (auto mode):
#   1. user-provided certs at $XCIND_PROXY_CONFIG_DIR/certs/wildcard.{crt,key}
#      (always wins — copied into the state cert when newer)
#   2. previously generated state cert for the same domain (fast path)
#   3. mkcert (if on PATH) → mints a locally-trusted wildcard
#   4. openssl (if on PATH) → self-signed wildcard fallback
#   5. error with installation guidance
#
# Custom mode copies the configured XCIND_PROXY_TLS_CERT_FILE / KEY_FILE.
# Disabled mode is a no-op.
#
# Returns 0 on success (or when TLS is disabled), non-zero on failure.
__xcind-proxy-ensure-certs() {
  local mode="${XCIND_PROXY_TLS_MODE:-auto}"
  [[ $mode == "disabled" ]] && return 0

  local domain="${XCIND_PROXY_DOMAIN:-localhost}"
  local certs_dir="$XCIND_PROXY_STATE_DIR/certs"
  local cert="$certs_dir/wildcard.crt"
  local key="$certs_dir/wildcard.key"
  local marker="$certs_dir/domain"

  mkdir -p "$certs_dir"

  # Regenerate if the cert was minted for a different domain.
  if [[ -f $marker ]]; then
    local recorded
    recorded=$(cat "$marker" 2>/dev/null || true)
    if [[ $recorded != "$domain" ]]; then
      rm -f "$cert" "$key"
    fi
  fi

  if [[ $mode == "custom" ]]; then
    if [[ -z ${XCIND_PROXY_TLS_CERT_FILE:-} || -z ${XCIND_PROXY_TLS_KEY_FILE:-} ]]; then
      echo "xcind-proxy: TLS mode is 'custom' but XCIND_PROXY_TLS_CERT_FILE / XCIND_PROXY_TLS_KEY_FILE are not set." >&2
      return 1
    fi
    if [[ ! -r $XCIND_PROXY_TLS_CERT_FILE ]]; then
      echo "xcind-proxy: cannot read cert file: $XCIND_PROXY_TLS_CERT_FILE" >&2
      return 1
    fi
    if [[ ! -r $XCIND_PROXY_TLS_KEY_FILE ]]; then
      echo "xcind-proxy: cannot read key file: $XCIND_PROXY_TLS_KEY_FILE" >&2
      return 1
    fi
    cp "$XCIND_PROXY_TLS_CERT_FILE" "$cert"
    cp "$XCIND_PROXY_TLS_KEY_FILE" "$key"
    chmod 600 "$key"
    printf '%s\n' "$domain" >"$marker"
    return 0
  fi

  # auto mode — check user-provided wildcard first (developer-curated
  # certs always win over previously-generated state), then fall back to
  # the state cache, then generate via mkcert / openssl.

  # 1. User-provided wildcard in config dir
  local user_cert="$XCIND_PROXY_CONFIG_DIR/certs/wildcard.crt"
  local user_key="$XCIND_PROXY_CONFIG_DIR/certs/wildcard.key"
  if [[ -r $user_cert && -r $user_key ]]; then
    # Refresh only when the user files changed (or we haven't copied yet)
    # so we don't rewrite the state cert on every `xcind-proxy up`.
    if [[ ! -s $cert || ! -s $key || $user_cert -nt $cert || $user_key -nt $key ]]; then
      cp "$user_cert" "$cert"
      cp "$user_key" "$key"
      chmod 600 "$key"
      echo "xcind-proxy: installed TLS cert from $XCIND_PROXY_CONFIG_DIR/certs/" >&2
    fi
    printf '%s\n' "$domain" >"$marker"
    return 0
  fi

  # 2. Reuse previously generated state cert for this domain
  if [[ -s $cert && -s $key ]]; then
    printf '%s\n' "$domain" >"$marker"
    return 0
  fi

  # 3. mkcert (preferred — produces locally-trusted cert)
  if command -v mkcert >/dev/null 2>&1; then
    echo "xcind-proxy: minting wildcard cert for *.${domain} via mkcert..." >&2
    if mkcert -cert-file "$cert" -key-file "$key" "*.${domain}" "${domain}" >&2; then
      chmod 600 "$key"
      printf '%s\n' "$domain" >"$marker"
      return 0
    fi
    echo "xcind-proxy: mkcert failed; falling back to self-signed." >&2
  fi

  # 4. openssl self-signed wildcard fallback
  if command -v openssl >/dev/null 2>&1; then
    echo "xcind-proxy: generating self-signed wildcard cert for *.${domain} via openssl..." >&2
    local cnf
    cnf=$(mktemp)
    cat >"$cnf" <<EOF
[req]
distinguished_name = req_dn
x509_extensions = v3_ext
prompt = no
[req_dn]
CN = *.${domain}
O = xcind
[v3_ext]
subjectAltName = DNS:*.${domain},DNS:${domain}
basicConstraints = CA:FALSE
keyUsage = digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth
EOF
    if openssl req -x509 -nodes -newkey rsa:2048 -days 825 \
      -keyout "$key" -out "$cert" -config "$cnf" >/dev/null 2>&1; then
      chmod 600 "$key"
      printf '%s\n' "$domain" >"$marker"
      rm -f "$cnf"
      return 0
    fi
    rm -f "$cnf"
    echo "xcind-proxy: openssl failed to generate self-signed cert." >&2
  fi

  echo "xcind-proxy: unable to provision a TLS certificate — install 'mkcert' or 'openssl'," >&2
  echo "             place cert/key at $user_cert and $user_key," >&2
  echo "             or set XCIND_PROXY_TLS_MODE=disabled." >&2
  return 1
}

# Ensure the proxy is fully operational: initialized, network exists, Traefik running.
# Skips auto-start if XCIND_PROXY_AUTO_START=0.
# $1: optional "strict" — when set, docker compose startup failures are
#     propagated as a non-zero return. Without it the function is non-fatal
#     so the EXECUTE hook path does not abort compose runs.
# All output goes to stderr to avoid interfering with hook stdout.
__xcind-proxy-ensure-running() {
  local strict_mode="${1:-}"

  # Opt-out: skip auto-start entirely
  if [[ ${XCIND_PROXY_AUTO_START:-1} == "0" ]]; then
    # Still ensure network exists for compose overlay compatibility
    __xcind-proxy-ensure-network 2>/dev/null || true
    return 0
  fi

  # Fast path: check if proxy is already running
  local running
  running=$(docker ps --filter label=xcind.component=proxy --filter status=running -q 2>/dev/null) || true
  if [ -n "$running" ]; then
    # Warn if config.sh is newer than generated files (stale)
    if [[ -f "$XCIND_PROXY_CONFIG_DIR/config.sh" && -f $XCIND_PROXY_COMPOSE ]] &&
      [[ "$XCIND_PROXY_CONFIG_DIR/config.sh" -nt $XCIND_PROXY_COMPOSE ]]; then
      echo "xcind-proxy: config.sh changed; run 'xcind-proxy up' to apply." >&2
    fi
    return 0
  fi

  # Ensure init has been done
  if [ ! -f "$XCIND_PROXY_COMPOSE" ]; then
    echo "xcind-proxy: Initializing proxy config at $XCIND_PROXY_CONFIG_DIR" >&2
  fi
  __xcind-proxy-ensure-init

  # Provision TLS certs (no-op when TLS mode = disabled).
  __xcind-proxy-ensure-certs || return $?

  # Start Traefik
  echo "xcind-proxy: Starting Traefik proxy..." >&2
  if ! docker compose -f "$XCIND_PROXY_COMPOSE" up -d 1>&2; then
    echo "xcind-proxy: Failed to start Traefik. Check 'xcind-proxy status' for details." >&2
    echo "xcind-proxy: Port ${XCIND_PROXY_HTTP_PORT:-80} may already be in use." >&2
    if [[ $strict_mode == "strict" ]]; then
      return 1
    fi
    # Non-fatal in EXECUTE hook: the compose overlay is still generated with correct labels
  fi
}

# --------------------------------------------------------------------------
# YAML Templates
# --------------------------------------------------------------------------

# Service block header — opens the service, attaches networks, starts labels.
# shellcheck disable=SC2016 # Template placeholders, not shell expansions
XCIND_PROXY_SERVICE_HEADER_TEMPLATE='  {compose_service}:
    networks:
      default: {}
      xcind-proxy: {}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=xcind-proxy"'

# HTTP router labels for a proxy export.
# shellcheck disable=SC2016
XCIND_PROXY_HTTP_ROUTER_TEMPLATE='      - "traefik.http.routers.{router}.rule=Host(`{hostname}`)"
      - "traefik.http.routers.{router}.entrypoints=web"
      - "traefik.http.routers.{router}.service={router}"
      - "traefik.http.services.{router}.loadbalancer.server.port={port}"'

# HTTP router labels that also trigger the redirect-to-HTTPS middleware
# (used when per-export tls=require). Redirect-only routers pin service to
# `noop@internal` so Traefik doesn't have to guess which backend service the
# router should resolve to — the request is redirected before ever reaching
# a backend, so no real service is needed.
# shellcheck disable=SC2016
XCIND_PROXY_HTTP_REDIRECT_ROUTER_TEMPLATE='      - "traefik.http.routers.{router}.rule=Host(`{hostname}`)"
      - "traefik.http.routers.{router}.entrypoints=web"
      - "traefik.http.routers.{router}.service=noop@internal"
      - "traefik.http.routers.{router}.middlewares=xcind-redirect-to-https@docker"'

# HTTPS router labels for a proxy export.
# shellcheck disable=SC2016
XCIND_PROXY_HTTPS_ROUTER_TEMPLATE='      - "traefik.http.routers.{router_https}.rule=Host(`{hostname}`)"
      - "traefik.http.routers.{router_https}.entrypoints=websecure"
      - "traefik.http.routers.{router_https}.tls=true"
      - "traefik.http.routers.{router_https}.service={router_https}"
      - "traefik.http.services.{router_https}.loadbalancer.server.port={port}"'

# Host/URL labels for a proxy export. Emitted once per export; includes the
# preferred scheme URL plus per-protocol sibling URLs when applicable.
# shellcheck disable=SC2016
XCIND_PROXY_EXPORT_HOST_LABEL='      - "xcind.export.{export}.host={hostname}"'
# shellcheck disable=SC2016
XCIND_PROXY_EXPORT_HTTP_URL_LABEL='      - "xcind.export.{export}.http.url=http://{hostname}"'
# shellcheck disable=SC2016
XCIND_PROXY_EXPORT_HTTPS_URL_LABEL='      - "xcind.export.{export}.https.url=https://{hostname}"'
# shellcheck disable=SC2016
XCIND_PROXY_EXPORT_URL_LABEL='      - "xcind.export.{export}.url={scheme}://{hostname}"'

# Apex router label fragments — symmetric to the per-export router fragments,
# but keyed by apex_router / apex_hostname.
# shellcheck disable=SC2016
XCIND_PROXY_APEX_HTTP_ROUTER_TEMPLATE='      - "traefik.http.routers.{apex_router}.rule=Host(`{apex_hostname}`)"
      - "traefik.http.routers.{apex_router}.entrypoints=web"
      - "traefik.http.routers.{apex_router}.service={apex_router}"
      - "traefik.http.services.{apex_router}.loadbalancer.server.port={port}"'
# Apex HTTP router labels that trigger the redirect-to-HTTPS middleware.
# Redirect-only routers pin service to `noop@internal` for the same reason
# as the per-export redirect template above.
# shellcheck disable=SC2016
XCIND_PROXY_APEX_HTTP_REDIRECT_ROUTER_TEMPLATE='      - "traefik.http.routers.{apex_router}.rule=Host(`{apex_hostname}`)"
      - "traefik.http.routers.{apex_router}.entrypoints=web"
      - "traefik.http.routers.{apex_router}.service=noop@internal"
      - "traefik.http.routers.{apex_router}.middlewares=xcind-redirect-to-https@docker"'
# shellcheck disable=SC2016
XCIND_PROXY_APEX_HTTPS_ROUTER_TEMPLATE='      - "traefik.http.routers.{apex_router_https}.rule=Host(`{apex_hostname}`)"
      - "traefik.http.routers.{apex_router_https}.entrypoints=websecure"
      - "traefik.http.routers.{apex_router_https}.tls=true"
      - "traefik.http.routers.{apex_router_https}.service={apex_router_https}"
      - "traefik.http.services.{apex_router_https}.loadbalancer.server.port={port}"'
# shellcheck disable=SC2016
XCIND_PROXY_APEX_HOST_LABEL='      - "xcind.apex.host={apex_hostname}"'
# shellcheck disable=SC2016
XCIND_PROXY_APEX_HTTP_URL_LABEL='      - "xcind.apex.http.url=http://{apex_hostname}"'
# shellcheck disable=SC2016
XCIND_PROXY_APEX_HTTPS_URL_LABEL='      - "xcind.apex.https.url=https://{apex_hostname}"'
# shellcheck disable=SC2016
XCIND_PROXY_APEX_URL_LABEL='      - "xcind.apex.url={scheme}://{apex_hostname}"'

# Shared HTTP→HTTPS redirect middleware. Appended to *every* rendered
# service block when any export uses tls=require — Traefik's Docker
# provider only loads labels from running containers, so a "first service
# only" emission would orphan the middleware reference whenever that
# service isn't running. Repeated definitions of the same middleware
# name/value are idempotent in Traefik.
XCIND_PROXY_REDIRECT_MIDDLEWARE_LABELS='      - "traefik.http.middlewares.xcind-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.xcind-redirect-to-https.redirectscheme.permanent=true"'

# --------------------------------------------------------------------------
# Export Entry Parsing
# --------------------------------------------------------------------------

# Parse a single XCIND_PROXY_EXPORTS entry into its components.
# Format: export_name[=compose_service][:port][;key=value[;key=value…]]
#
# Sets: _export_name, _compose_service, _port (empty if not specified),
#       _type (defaults to "proxied"),
#       _tls  (defaults to "auto", only meaningful when _type=proxied)
#
# Recognized metadata keys:
#   type = proxied | assigned
#   tls  = auto | require | disable
#
# Unknown keys and invalid values produce an error and return 1.
__xcind-proxy-parse-entry() {
  local entry="$1"
  local orig="$entry"
  local right meta=""

  # Reset metadata defaults on every call — must not leak between invocations.
  _type="proxied"
  _tls="auto"

  # Strip metadata tail (everything after the first ';').
  if [[ $entry == *";"* ]]; then
    meta="${entry#*;}"
    entry="${entry%%;*}"
  fi

  # Split on = (export_name=compose_service_and_port or just export_and_port)
  if [[ $entry == *=* ]]; then
    _export_name="${entry%%=*}"
    right="${entry#*=}"
  else
    right="$entry"
    _export_name=""
  fi

  # Split right side on : (service:port or just service)
  if [[ $right == *:* ]]; then
    local svc_part="${right%%:*}"
    _port="${right#*:}"
  else
    local svc_part="$right"
    _port=""
  fi

  _compose_service="$svc_part"

  # If no = was present, export name = compose service name
  if [ -z "$_export_name" ]; then
    _export_name="$_compose_service"
  fi

  # Parse metadata key=value pairs
  if [[ -n $meta ]]; then
    # Save and restore IFS around the split (see __xcind-resolve-tools for
    # the same pattern; `unset IFS` would expose the inherited value).
    local _old_ifs="$IFS"
    IFS=';'
    local pairs
    # shellcheck disable=SC2206
    pairs=($meta)
    IFS="$_old_ifs"
    local pair key val
    for pair in "${pairs[@]}"; do
      [[ -z $pair ]] && continue
      key="${pair%%=*}"
      val="${pair#*=}"
      case "$key" in
      type)
        case "$val" in
        proxied | assigned) _type="$val" ;;
        *)
          __xcind-debug "parse-entry: invalid type='$val' in '$orig'"
          echo "Error: invalid XCIND_PROXY_EXPORTS type '$val' in '$orig' (expected 'proxied' or 'assigned')" >&2
          return 1
          ;;
        esac
        ;;
      tls)
        case "$val" in
        auto | require | disable) _tls="$val" ;;
        *)
          echo "Error: invalid XCIND_PROXY_EXPORTS tls '$val' in '$orig' (expected 'auto', 'require', or 'disable')" >&2
          return 1
          ;;
        esac
        ;;
      *)
        __xcind-debug "parse-entry: unknown attribute='$key' in '$orig'"
        echo "Error: unknown XCIND_PROXY_EXPORTS attribute '$key' in '$orig'" >&2
        return 1
        ;;
      esac
    done
  fi
}

# --------------------------------------------------------------------------
# Port Inference
# --------------------------------------------------------------------------

# Infer the container port for a compose service from resolved-config.yaml.
# Requires yq.
#
# Usage:
#   port=$(__xcind-proxy-infer-port "web" /path/to/resolved-config.yaml)
__xcind-proxy-infer-port() {
  local service="$1"
  local resolved_config="$2"

  local port_count
  port_count=$(yq ".services.\"$service\".ports | length" "$resolved_config" 2>/dev/null) || port_count=0

  if [ "$port_count" -eq 0 ]; then
    echo "Error: Service '$service' has no port mappings. Specify port explicitly." >&2
    return 1
  elif [ "$port_count" -gt 1 ]; then
    echo "Error: Service '$service' has multiple port mappings. Specify port explicitly." >&2
    return 1
  fi

  # Extract the target (container) port from the single port mapping
  local target
  target=$(yq ".services.\"$service\".ports[0].target" "$resolved_config" 2>/dev/null)

  if [ -z "$target" ] || [ "$target" = "null" ]; then
    # Try published format (string like "80:8080")
    local port_str
    port_str=$(yq ".services.\"$service\".ports[0]" "$resolved_config" 2>/dev/null)
    if [[ $port_str == *:* ]]; then
      target="${port_str##*:}"
    else
      target="$port_str"
    fi
  fi

  echo "$target"
}

# --------------------------------------------------------------------------
# Service Validation
# --------------------------------------------------------------------------

# Check that a compose service exists in resolved-config.yaml.
__xcind-proxy-validate-service() {
  local service="$1"
  local resolved_config="$2"

  local exists
  exists=$(yq ".services | has(\"$service\")" "$resolved_config" 2>/dev/null)

  if [ "$exists" != "true" ]; then
    local available
    available=$(__xcind-list-services "$resolved_config" | tr '\n' ', ' | sed 's/,$//')
    echo "Error: Service '$service' not found in compose config. Available services: $available" >&2
    return 1
  fi
}

# --------------------------------------------------------------------------
# Hook Function
# --------------------------------------------------------------------------

# Resolve the effective TLS mode for a single export, given the current
# proxy-level TLS setting. Sets _effective_tls to one of:
#   both    — emit HTTP + HTTPS routers
#   https   — emit HTTPS router; HTTP router is a redirect to HTTPS
#   http    — emit HTTP router only (no HTTPS)
#
# Inputs: _tls (export-level), $1 (proxy-level TLS mode).
__xcind-proxy-resolve-export-tls() {
  local proxy_tls="$1"
  if [[ $proxy_tls == "disabled" ]]; then
    _effective_tls="http"
    return 0
  fi
  case "$_tls" in
  disable) _effective_tls="http" ;;
  require) _effective_tls="https" ;;
  auto | *) _effective_tls="both" ;;
  esac
}

# Render the proxied hostname for an export. Single source of truth shared by
# the GENERATE hook (which feeds it into router rules + labels) and the
# introspection path (__xcind-proxy-json-for-app) so the two never drift.
#
# App name and domain default to XCIND_APP / XCIND_PROXY_DOMAIN but may be
# passed explicitly ($2, $3) so callers need not mutate those globals.
# Requires XCIND_APP_URL_TEMPLATE (and optional XCIND_WORKSPACE) in scope.
#
# Usage:
#   hostname=$(__xcind-proxy-export-hostname "web")
#   hostname=$(__xcind-proxy-export-hostname "web" "$app_name" "$domain")
__xcind-proxy-export-hostname() {
  local export_name="$1"
  local app_name="${2:-$XCIND_APP}"
  local domain="${3:-$XCIND_PROXY_DOMAIN}"
  __xcind-render-template "$XCIND_APP_URL_TEMPLATE" \
    workspace "${XCIND_WORKSPACE:-}" app "$app_name" \
    export "$export_name" domain "$domain"
}

# Echo the preferred URL scheme (http|https) for a resolved effective TLS
# mode. https whenever HTTPS is reachable (both/https), http otherwise.
# Mirrors the canonical-URL rule in the GENERATE hook.
__xcind-proxy-preferred-scheme() {
  case "$1" in
  both | https) echo "https" ;;
  *) echo "http" ;;
  esac
}

# Build a JSON object of proxied exports for an app, keyed by export name:
#   { "<name>": { compose_service, container_port, url, tls } }
#
# URLs are computed from XCIND_APP_URL_TEMPLATE (not read off running
# containers) so they resolve even when nothing is up — the proxied-export
# analogue of __xcind-assigned-json-for-app. container_port is inferred from
# resolved-config.yaml when not declared, and is null when it cannot be
# determined (introspection never fails on a missing port). `tls` is the
# declared per-export mode (auto|require|disable).
#
# Returns "{}" when there are no proxied exports or jq is unavailable. Always
# invoked via command substitution, so sourcing the global proxy config and
# defaulting the domain stay contained to that subshell (mirrors the hook,
# which runs the same way) — app name and domain are passed explicitly into
# the hostname helper rather than mutating the globals here.
__xcind-proxy-json-for-app() {
  local app_root="$1"
  if ! command -v jq &>/dev/null; then
    echo "{}"
    return 0
  fi
  if [[ -z ${XCIND_PROXY_EXPORTS+set} || ${#XCIND_PROXY_EXPORTS[@]} -eq 0 ]]; then
    echo "{}"
    return 0
  fi

  # Establish domain + TLS mode exactly as the GENERATE hook does.
  local domain="${XCIND_PROXY_DOMAIN:-localhost}"
  local global_config="${XCIND_PROXY_CONFIG_DIR}/config.sh"
  if [ -f "$global_config" ]; then
    # shellcheck disable=SC1090
    source "$global_config"
    domain="${XCIND_PROXY_DOMAIN:-$domain}"
  fi
  local proxy_tls_mode="${XCIND_PROXY_TLS_MODE:-auto}"

  # App name fallback mirrors __xcind-build-config-json's metadata.
  local app_name="${XCIND_APP:-$(basename "$app_root")}"

  # XCIND_CACHE_DIR may be unset when the config JSON is built outside the
  # full prepare pipeline; the -f check below then simply skips inference.
  local resolved_config="${XCIND_CACHE_DIR:-}/resolved-config.yaml"

  local result="{}"
  local entry
  for entry in "${XCIND_PROXY_EXPORTS[@]}"; do
    local _export_name _compose_service _port _type _tls _effective_tls
    __xcind-proxy-parse-entry "$entry" 2>/dev/null || continue
    [[ $_type == "proxied" ]] || continue

    # Best-effort container port: declared value, else inferred, else null.
    local cport="$_port"
    if [[ -z $cport && -f $resolved_config ]]; then
      cport=$(__xcind-proxy-infer-port "$_compose_service" "$resolved_config" 2>/dev/null) || cport=""
    fi
    local cport_json="null"
    [[ -n $cport && $cport != "null" ]] && cport_json="$cport"

    __xcind-proxy-resolve-export-tls "$proxy_tls_mode"
    local hostname scheme url
    hostname=$(__xcind-proxy-export-hostname "$_export_name" "$app_name" "$domain")
    scheme=$(__xcind-proxy-preferred-scheme "$_effective_tls")
    url="$scheme://$hostname"

    result=$(printf '%s' "$result" | jq \
      --arg name "$_export_name" \
      --arg svc "$_compose_service" \
      --argjson cport "$cport_json" \
      --arg url "$url" \
      --arg tls "$_tls" \
      '. + {($name): {compose_service: $svc, container_port: $cport, url: $url, tls: $tls}}')
  done
  printf '%s' "$result"
}

# Main hook function called by the xcind pipeline on cache miss.
# Reads pipeline env vars and generates compose.proxy.yaml.
xcind-proxy-hook() {
  local app_root="$1"

  # Check if exports are defined (guard against unset under set -u)
  if [[ -z ${XCIND_PROXY_EXPORTS+set} || ${#XCIND_PROXY_EXPORTS[@]} -eq 0 ]]; then
    return 0
  fi

  # Default domain and source global config
  XCIND_PROXY_DOMAIN="${XCIND_PROXY_DOMAIN:-localhost}"
  local global_config="${XCIND_PROXY_CONFIG_DIR}/config.sh"
  if [ -f "$global_config" ]; then
    # shellcheck disable=SC1090
    source "$global_config"
  fi

  local proxy_tls_mode="${XCIND_PROXY_TLS_MODE:-auto}"

  # Require yq
  if ! command -v yq &>/dev/null; then
    echo "Error: yq is required for proxy hook but was not found." >&2
    return 1
  fi

  local resolved_config="$XCIND_CACHE_DIR/resolved-config.yaml"

  local apex_enabled=false
  if [[ -n ${XCIND_APP_APEX_URL_TEMPLATE:-} ]]; then
    apex_enabled=true
  fi

  # Parse all export entries and group by compose service
  local -a export_names=()
  local -a compose_services=()
  local -a ports=()
  local -a hostnames=()
  local -a routers_http=()
  local -a routers_https=()
  local -a export_tls=() # one of: both | https | http
  local apex_hostname=""
  local apex_router_http=""
  local apex_router_https=""
  local apex_tls="" # both | https | http — derived from primary export

  local entry
  local is_first_proxied=true
  for entry in "${XCIND_PROXY_EXPORTS[@]}"; do
    local _export_name _compose_service _port _type _tls _effective_tls
    __xcind-proxy-parse-entry "$entry" || return 1

    # This hook only handles proxied entries. Assigned entries flow through
    # xcind-assigned-hook, which reads the same array.
    [[ $_type == "proxied" ]] || continue

    # Validate service exists
    __xcind-proxy-validate-service "$_compose_service" "$resolved_config" || return 1

    # Resolve port
    if [ -z "$_port" ]; then
      _port=$(__xcind-proxy-infer-port "$_compose_service" "$resolved_config") || return 1
    fi

    # Validate resolved port: strip a known Compose protocol suffix (e.g.
    # 80/tcp) and then require a positive integer. Any other non-numeric
    # value is an error — callers should specify a numeric target port.
    _port="${_port%%/*}"
    if ! [[ $_port =~ ^[0-9]+$ ]] || [ "$_port" -lt 1 ] || [ "$_port" -gt 65535 ]; then
      echo "Error: XCIND_PROXY_EXPORTS port for '$_export_name' is not a valid port number (got: '$_port'). Specify a numeric container port explicitly." >&2
      return 1
    fi

    # Resolve effective TLS for this export
    __xcind-proxy-resolve-export-tls "$proxy_tls_mode"

    # Generate hostname (shared with the introspection path)
    local hostname
    hostname=$(__xcind-proxy-export-hostname "$_export_name")

    # Generate router names (http + https — the literal suffix is part of
    # the name, not the entrypoint; see ADR-0008 router naming convention).
    local router_http router_https
    router_http=$(__xcind-render-template "$XCIND_ROUTER_TEMPLATE" \
      workspace "${XCIND_WORKSPACE:-}" app "$XCIND_APP" \
      export "$_export_name" protocol "http")
    router_https=$(__xcind-render-template "$XCIND_ROUTER_TEMPLATE" \
      workspace "${XCIND_WORKSPACE:-}" app "$XCIND_APP" \
      export "$_export_name" protocol "https")

    # Generate apex hostname and routers for the first proxied entry only.
    # Order within the unified array still selects the apex anchor, but an
    # assigned entry placed earlier does not consume the apex slot.
    if [[ $is_first_proxied == true && $apex_enabled == true ]]; then
      apex_hostname=$(__xcind-render-template "$XCIND_APP_APEX_URL_TEMPLATE" \
        workspace "${XCIND_WORKSPACE:-}" app "$XCIND_APP" \
        domain "$XCIND_PROXY_DOMAIN")
      apex_router_http=$(__xcind-render-template "$XCIND_APEX_ROUTER_TEMPLATE" \
        workspace "${XCIND_WORKSPACE:-}" app "$XCIND_APP" \
        protocol "http")
      apex_router_https=$(__xcind-render-template "$XCIND_APEX_ROUTER_TEMPLATE" \
        workspace "${XCIND_WORKSPACE:-}" app "$XCIND_APP" \
        protocol "https")
      apex_tls="$_effective_tls"
    fi
    is_first_proxied=false

    export_names+=("$_export_name")
    compose_services+=("$_compose_service")
    ports+=("$_port")
    hostnames+=("$hostname")
    routers_http+=("$router_http")
    routers_https+=("$router_https")
    export_tls+=("$_effective_tls")
  done

  # Nothing proxied after filtering: no compose overlay, no -f flag.
  [[ ${#export_names[@]} -gt 0 ]] || return 0

  # Determine whether any export (incl. apex) needs the redirect middleware.
  local needs_redirect_middleware=false
  local t
  for t in "${export_tls[@]}"; do
    if [[ $t == "https" ]]; then
      needs_redirect_middleware=true
      break
    fi
  done

  # Build output grouped by compose service
  local output="services:"
  local -a seen_services=()

  local i=0
  while [ "$i" -lt "${#export_names[@]}" ]; do
    local svc="${compose_services[$i]}"

    # Check if we already rendered this compose service
    local already_seen=false
    local s
    for s in "${seen_services[@]+"${seen_services[@]}"}"; do
      if [ "$s" = "$svc" ]; then
        already_seen=true
        break
      fi
    done

    if [ "$already_seen" = true ]; then
      i=$((i + 1))
      continue
    fi

    seen_services+=("$svc")

    # Open the service block (networks + shared label prelude).
    local service_block
    service_block=$(__xcind-render-template "$XCIND_PROXY_SERVICE_HEADER_TEMPLATE" \
      compose_service "$svc")

    # Emit the shared redirect middleware on every rendered service block
    # when at least one export uses tls=require. Traefik's Docker provider
    # only discovers labels from running containers, so emitting this on a
    # single "first" service can leave other independently-started services
    # without the middleware they reference. Repeated definitions with the
    # same name/value are idempotent in Traefik.
    if [[ $needs_redirect_middleware == true ]]; then
      service_block+=$'\n'"$XCIND_PROXY_REDIRECT_MIDDLEWARE_LABELS"
    fi

    # Walk every export targeting this compose service, appending router +
    # URL labels for each. The first export on the service is also where the
    # apex routers/labels land (when it is index 0 of the overall list).
    local j=0
    while [ "$j" -lt "${#export_names[@]}" ]; do
      if [ "${compose_services[$j]}" = "$svc" ]; then
        local e_router_http="${routers_http[$j]}"
        local e_router_https="${routers_https[$j]}"
        local e_hostname="${hostnames[$j]}"
        local e_port="${ports[$j]}"
        local e_export="${export_names[$j]}"
        local e_tls="${export_tls[$j]}"

        local fragment
        case "$e_tls" in
        http)
          fragment=$(__xcind-render-template "$XCIND_PROXY_HTTP_ROUTER_TEMPLATE" \
            router "$e_router_http" hostname "$e_hostname" port "$e_port")
          service_block+=$'\n'"$fragment"
          ;;
        both)
          fragment=$(__xcind-render-template "$XCIND_PROXY_HTTP_ROUTER_TEMPLATE" \
            router "$e_router_http" hostname "$e_hostname" port "$e_port")
          service_block+=$'\n'"$fragment"
          fragment=$(__xcind-render-template "$XCIND_PROXY_HTTPS_ROUTER_TEMPLATE" \
            router_https "$e_router_https" hostname "$e_hostname" port "$e_port")
          service_block+=$'\n'"$fragment"
          ;;
        https)
          fragment=$(__xcind-render-template "$XCIND_PROXY_HTTP_REDIRECT_ROUTER_TEMPLATE" \
            router "$e_router_http" hostname "$e_hostname")
          service_block+=$'\n'"$fragment"
          fragment=$(__xcind-render-template "$XCIND_PROXY_HTTPS_ROUTER_TEMPLATE" \
            router_https "$e_router_https" hostname "$e_hostname" port "$e_port")
          service_block+=$'\n'"$fragment"
          ;;
        esac

        # Apex routers — rendered once, on the first export (index 0 overall)
        if [[ $j -eq 0 && $apex_enabled == true ]]; then
          case "$apex_tls" in
          http)
            fragment=$(__xcind-render-template "$XCIND_PROXY_APEX_HTTP_ROUTER_TEMPLATE" \
              apex_router "$apex_router_http" apex_hostname "$apex_hostname" port "$e_port")
            service_block+=$'\n'"$fragment"
            ;;
          both)
            fragment=$(__xcind-render-template "$XCIND_PROXY_APEX_HTTP_ROUTER_TEMPLATE" \
              apex_router "$apex_router_http" apex_hostname "$apex_hostname" port "$e_port")
            service_block+=$'\n'"$fragment"
            fragment=$(__xcind-render-template "$XCIND_PROXY_APEX_HTTPS_ROUTER_TEMPLATE" \
              apex_router_https "$apex_router_https" apex_hostname "$apex_hostname" port "$e_port")
            service_block+=$'\n'"$fragment"
            ;;
          https)
            fragment=$(__xcind-render-template "$XCIND_PROXY_APEX_HTTP_REDIRECT_ROUTER_TEMPLATE" \
              apex_router "$apex_router_http" apex_hostname "$apex_hostname")
            service_block+=$'\n'"$fragment"
            fragment=$(__xcind-render-template "$XCIND_PROXY_APEX_HTTPS_ROUTER_TEMPLATE" \
              apex_router_https "$apex_router_https" apex_hostname "$apex_hostname" port "$e_port")
            service_block+=$'\n'"$fragment"
            ;;
          esac
        fi

        # xcind.export.* host/url labels — one set per export.
        # `.http.url` is emitted whenever the export has an HTTP router
        # (always, for proxied exports — redirect-only counts) so consumers
        # see a stable HTTP entry point. `.https.url` is emitted only when
        # an HTTPS router actually exists. `.url` is the preferred-scheme
        # canonical (https when TLS is reachable, otherwise http).
        local preferred_scheme
        preferred_scheme=$(__xcind-proxy-preferred-scheme "$e_tls")
        fragment=$(__xcind-render-template "$XCIND_PROXY_EXPORT_HOST_LABEL" \
          export "$e_export" hostname "$e_hostname")
        service_block+=$'\n'"$fragment"
        fragment=$(__xcind-render-template "$XCIND_PROXY_EXPORT_HTTP_URL_LABEL" \
          export "$e_export" hostname "$e_hostname")
        service_block+=$'\n'"$fragment"
        if [[ $e_tls == "https" || $e_tls == "both" ]]; then
          fragment=$(__xcind-render-template "$XCIND_PROXY_EXPORT_HTTPS_URL_LABEL" \
            export "$e_export" hostname "$e_hostname")
          service_block+=$'\n'"$fragment"
        fi
        fragment=$(__xcind-render-template "$XCIND_PROXY_EXPORT_URL_LABEL" \
          export "$e_export" hostname "$e_hostname" scheme "$preferred_scheme")
        service_block+=$'\n'"$fragment"

        # xcind.apex.* host/url labels — rendered once on the first export.
        # Symmetric with the per-export labels above: `.http.url` is always
        # emitted (an HTTP apex router always exists, even as a redirect),
        # `.https.url` only when an HTTPS apex router exists.
        if [[ $j -eq 0 && $apex_enabled == true ]]; then
          local apex_preferred_scheme="http"
          [[ $apex_tls == "both" || $apex_tls == "https" ]] && apex_preferred_scheme="https"
          fragment=$(__xcind-render-template "$XCIND_PROXY_APEX_HOST_LABEL" \
            apex_hostname "$apex_hostname")
          service_block+=$'\n'"$fragment"
          fragment=$(__xcind-render-template "$XCIND_PROXY_APEX_HTTP_URL_LABEL" \
            apex_hostname "$apex_hostname")
          service_block+=$'\n'"$fragment"
          if [[ $apex_tls == "https" || $apex_tls == "both" ]]; then
            fragment=$(__xcind-render-template "$XCIND_PROXY_APEX_HTTPS_URL_LABEL" \
              apex_hostname "$apex_hostname")
            service_block+=$'\n'"$fragment"
          fi
          fragment=$(__xcind-render-template "$XCIND_PROXY_APEX_URL_LABEL" \
            apex_hostname "$apex_hostname" scheme "$apex_preferred_scheme")
          service_block+=$'\n'"$fragment"
        fi
      fi
      j=$((j + 1))
    done

    output+=$'\n\n'"$service_block"
    i=$((i + 1))
  done

  # Append network footer
  output+=$'\n\nnetworks:\n  xcind-proxy:\n    external: true\n'

  # Write to generated dir
  echo "$output" >"$XCIND_GENERATED_DIR/compose.proxy.yaml"

  # Print compose flag to stdout
  echo "-f $XCIND_GENERATED_DIR/compose.proxy.yaml"
}

# --------------------------------------------------------------------------
# Execute Hook
# --------------------------------------------------------------------------

# EXECUTE hook: ensure proxy is running before docker compose executes.
# Runs on every invocation (not cached). Skips unless XCIND_PROXY_EXPORTS
# contains at least one `type=proxied` entry — a config with only
# `type=assigned` entries needs no Traefik.
__xcind-proxy-execute-hook() {
  # shellcheck disable=SC2034  # app_root required by hook interface
  local app_root="$1"

  if [[ -z ${XCIND_PROXY_EXPORTS+set} || ${#XCIND_PROXY_EXPORTS[@]} -eq 0 ]]; then
    return 0
  fi

  # Parse defensively; validation errors are surfaced by the GENERATE hook.
  local entry _export_name _compose_service _port _type
  local has_proxied=0
  for entry in "${XCIND_PROXY_EXPORTS[@]}"; do
    if __xcind-proxy-parse-entry "$entry" 2>/dev/null; then
      if [[ $_type == "proxied" ]]; then
        has_proxied=1
        break
      fi
    fi
  done
  [[ $has_proxied -eq 1 ]] || return 0

  __xcind-proxy-ensure-running
}
