#!/usr/bin/env bash
# xcind-hostenv-lib.bash — EXECUTE hook that writes a host-view env file.
#
# Emits the discovery variable set (XCIND_{APP}_{EXPORT}_*) with host-flavored
# values for assigned exports — _HOST=127.0.0.1 + the allocated host port —
# while proxied/apex hosts stay the routable proxied hostname. Host-run
# processes (mise/direnv) then compose the same DATABASE_URL etc. as containers
# do: dotenv loaders never override a real OS env var, and Compose
# `environment:` beats `env_file:`, so one committed expression resolves to the
# container endpoint inside a container and the host endpoint on the host.
#
# The variable set comes from the shared __xcind-discovery-build-pairs seam
# (xcind-discovery-lib.bash) so the host and container views never drift.
#
# Opt-in: enabled iff XCIND_HOST_ENV_FILE is set non-empty (typically in
# .xcind.sh). Unset => no-op (zero working-tree writes for existing users).
# Write mode is the explicit variable XCIND_HOST_ENV_MODE (own|block), default
# own; it is NEVER inferred from the filename.
#
# This file is auto-sourced by xcind-lib.bash; the EXECUTE hook is registered in
# XCIND_HOOKS_EXECUTE and runs after the assigned-port allocation, so host ports
# are live on every run.

# Markers delimiting the xcind-managed region in block mode.
__XCIND_HOSTENV_BEGIN='# >>> xcind >>>'
__XCIND_HOSTENV_END='# <<< xcind <<<'

# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

# Quote a dotenv value only when it needs it. Bare tokens (the common case:
# 127.0.0.1, ports, hostnames, scheme://host:port URLs) are emitted unquoted;
# an empty value becomes "". Anything else is double-quoted with backslash and
# double-quote escaped, so dotenv loaders read back the literal value. Bash 3.2
# safe (no ${var^^}).
__xcind-hostenv-quote-value() {
  local v="$1"
  case "$v" in
  '')
    printf '""'
    ;;
  *[!A-Za-z0-9._:/@-]*)
    v="${v//\\/\\\\}" # escape backslashes first
    v="${v//\"/\\\"}" # then double quotes
    printf '"%s"' "$v"
    ;;
  *)
    printf '%s' "$v"
    ;;
  esac
}

# Render the dotenv body for the given KEY=VALUE pairs, values quoted as needed.
# Prints KEY=VALUE per line to stdout; no header/markers (callers add framing).
# Bash 3.2 safe: a zero-argument call simply prints nothing.
__xcind-hostenv-render() {
  local pair key val
  for pair in "$@"; do
    key="${pair%%=*}"
    val="${pair#*=}"
    printf '%s=%s\n' "$key" "$(__xcind-hostenv-quote-value "$val")"
  done
}

# Frame the body for own mode: a do-not-edit header followed by the body.
__xcind-hostenv-frame-own() {
  local body="$1"
  local header="# Generated by xcind — do not edit. Source: XCIND_HOST_ENV_FILE (mode=own)."
  if [[ -n $body ]]; then
    printf '%s\n%s' "$header" "$body"
  else
    printf '%s' "$header"
  fi
}

# Frame the body for block mode: the body wrapped in the begin/end markers (the
# markers are the framing, so no separate header line).
__xcind-hostenv-frame-block() {
  local body="$1"
  if [[ -n $body ]]; then
    printf '%s\n%s\n%s' "$__XCIND_HOSTENV_BEGIN" "$body" "$__XCIND_HOSTENV_END"
  else
    printf '%s\n%s' "$__XCIND_HOSTENV_BEGIN" "$__XCIND_HOSTENV_END"
  fi
}

# --------------------------------------------------------------------------
# Writers
# --------------------------------------------------------------------------

# Atomic write: ensure the parent dir exists, write a process-unique sibling
# temp, then mv(1) it over the target. The temp is removed on any failure.
__xcind-hostenv-atomic-write() {
  local target="$1" content="$2"
  local dir tmp
  dir=$(dirname -- "$target")
  if [[ ! -d $dir ]]; then
    mkdir -p -- "$dir" || {
      echo "xcind: cannot create directory for XCIND_HOST_ENV_FILE: $dir" >&2
      return 1
    }
  fi
  tmp=$(mktemp "${target}.XXXXXXXXXX") || return 1
  printf '%s\n' "$content" >"$tmp" || {
    rm -f -- "$tmp"
    return 1
  }
  mv -- "$tmp" "$target" || {
    rm -f -- "$tmp"
    return 1
  }
}

# own mode: xcind fully owns the file. Render header + body; if the target is
# already byte-identical, leave it untouched (no mtime churn); else atomic-write.
__xcind-hostenv-write-own() {
  local target="$1" body="$2" content
  content=$(__xcind-hostenv-frame-own "$body")
  if [[ -f $target ]] && [[ "$(<"$target")" == "$content" ]]; then
    return 0
  fi
  __xcind-hostenv-atomic-write "$target" "$content"
}

# Print $target with the first begin..end marked region (inclusive) replaced by
# $block, preserving every other line. Assumes the begin marker is present.
__xcind-hostenv-replace-block() {
  local target="$1" block="$2"
  local line in_block=0 done_block=0 out=""
  while IFS= read -r line || [[ -n $line ]]; do
    if [[ $done_block -eq 0 && $in_block -eq 0 && $line == "$__XCIND_HOSTENV_BEGIN" ]]; then
      in_block=1
      out+="$block"$'\n'
      continue
    fi
    if [[ $in_block -eq 1 ]]; then
      if [[ $line == "$__XCIND_HOSTENV_END" ]]; then
        in_block=0
        done_block=1
      fi
      continue
    fi
    out+="$line"$'\n'
  done <"$target"
  printf '%s' "${out%$'\n'}"
}

# block mode: rewrite only the xcind-marked region, preserving all other lines.
# Append the block once (separated by a blank line) when the markers are absent.
# Idempotent: skip the write when the result is byte-identical to the target.
__xcind-hostenv-write-block() {
  local target="$1" body="$2" block content existing=""
  block=$(__xcind-hostenv-frame-block "$body")
  [[ -f $target ]] && existing=$(<"$target")

  if [[ -f $target ]] && grep -qF -- "$__XCIND_HOSTENV_BEGIN" "$target"; then
    content=$(__xcind-hostenv-replace-block "$target" "$block")
  elif [[ -n $existing ]]; then
    content="${existing}"$'\n\n'"${block}"
  else
    content="$block"
  fi

  if [[ -f $target ]] && [[ $existing == "$content" ]]; then
    return 0
  fi
  __xcind-hostenv-atomic-write "$target" "$content"
}

# --------------------------------------------------------------------------
# Execute Hook
# --------------------------------------------------------------------------

# EXECUTE hook: write the host-view env file when XCIND_HOST_ENV_FILE is set.
# Runs on every invocation (not cached), after assigned ports are allocated.
__xcind-hostenv-execute-hook() {
  local app_root="$1"
  local target="${XCIND_HOST_ENV_FILE:-}"
  [[ -z $target ]] && return 0 # opt-in gate

  # Resolve a relative path against the app root.
  [[ $target != /* ]] && target="$app_root/$target"

  local mode="${XCIND_HOST_ENV_MODE:-own}"
  if [[ $mode != own && $mode != block ]]; then
    echo "xcind: invalid XCIND_HOST_ENV_MODE '$mode' (expected: own|block)" >&2
    return 1
  fi

  # Collect host-view pairs from the shared discovery seam.
  local -a env_lines=()
  local _pair
  while IFS= read -r _pair; do
    [[ -n $_pair ]] && env_lines+=("$_pair")
  done < <(__xcind-discovery-build-pairs "$app_root" host)

  # Render the dotenv body once (shared by both modes). The +"" guard keeps the
  # empty-array expansion safe under set -u on Bash 3.2.
  local body
  body=$(__xcind-hostenv-render "${env_lines[@]+"${env_lines[@]}"}")

  case "$mode" in
  own) __xcind-hostenv-write-own "$target" "$body" ;;
  block) __xcind-hostenv-write-block "$target" "$body" ;;
  esac
}
