#!/usr/bin/env bash
# xcind-proxy-lib.bash — Proxy hooks and shared lifecycle functions
#
# Provides two hooks:
#   xcind-proxy-hook (GENERATE) — generates Traefik proxy configuration
#   __xcind-proxy-execute-hook (EXECUTE) — ensures proxy is running
#
# Also provides __xcind-proxy-ensure-* functions used by both the hooks
# and the xcind-proxy CLI to manage proxy infrastructure.
#
# This file is auto-sourced by xcind-lib.bash. Hooks are registered by
# default — apps only need to declare XCIND_PROXY_EXPORTS to use them.

# --------------------------------------------------------------------------
# Shared Constants
# --------------------------------------------------------------------------

XCIND_PROXY_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/xcind/proxy"
XCIND_PROXY_STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/xcind/proxy"
XCIND_PROXY_COMPOSE="${XCIND_PROXY_STATE_DIR}/docker-compose.yaml"
XCIND_PROXY_NETWORK="xcind-proxy"
# Backward compat alias for messages and hook references
# shellcheck disable=SC2034 # Used externally by tests and CLI
XCIND_PROXY_DIR="$XCIND_PROXY_CONFIG_DIR"

# --------------------------------------------------------------------------
# Proxy Lifecycle Functions
# --------------------------------------------------------------------------

# Ensure the xcind-proxy Docker network exists.
__xcind-proxy-ensure-network() {
  if docker network inspect "$XCIND_PROXY_NETWORK" &>/dev/null; then
    return 0
  fi

  if ! docker network create "$XCIND_PROXY_NETWORK" >/dev/null; then
    echo "Error: Failed to create Docker network '$XCIND_PROXY_NETWORK'." >&2
    echo "Check that Docker is running and you have permission to create networks." >&2
    return 1
  fi
}

# Write (or overwrite) config.sh with the current XCIND_PROXY_* values.
# Callers must set the variables before calling this function.
__xcind-proxy-write-config() {
  cat >"$XCIND_PROXY_CONFIG_DIR/config.sh" <<EOF
# xcind-proxy global configuration
# This file is regenerated by \`xcind-proxy init\` when flags are passed.

# Domain suffix for generated hostnames (.localhost = zero DNS config, RFC 6761)
XCIND_PROXY_DOMAIN="${XCIND_PROXY_DOMAIN:-localhost}"

# Traefik Docker image
XCIND_PROXY_IMAGE="${XCIND_PROXY_IMAGE:-traefik:v3}"

# Host port for HTTP traffic
XCIND_PROXY_HTTP_PORT="${XCIND_PROXY_HTTP_PORT:-80}"

# Enable Traefik dashboard
XCIND_PROXY_DASHBOARD="${XCIND_PROXY_DASHBOARD:-false}"

# Dashboard port (only used if dashboard is enabled)
XCIND_PROXY_DASHBOARD_PORT="${XCIND_PROXY_DASHBOARD_PORT:-8080}"
EOF
}

# Ensure proxy infrastructure files exist.
# Creates config.sh (if missing) in XCIND_PROXY_CONFIG_DIR,
# docker-compose.yaml and traefik.yaml in XCIND_PROXY_STATE_DIR.
# Note: xcind-proxy init may regenerate config.sh explicitly via
# __xcind-proxy-write-config when CLI flags are passed.
# Calls __xcind-proxy-ensure-network after generating files.
__xcind-proxy-ensure-init() {
  mkdir -p "$XCIND_PROXY_CONFIG_DIR" "$XCIND_PROXY_STATE_DIR"

  # Write config.sh only if it doesn't exist (preserves user edits)
  if [ ! -f "$XCIND_PROXY_CONFIG_DIR/config.sh" ]; then
    __xcind-proxy-write-config
  fi

  # Source config for variable expansion
  # shellcheck disable=SC1091
  source "$XCIND_PROXY_CONFIG_DIR/config.sh"

  # Write docker-compose.yaml (always regenerated)
  local dashboard_command=""
  local dashboard_port=""
  if [ "${XCIND_PROXY_DASHBOARD:-false}" = "true" ]; then
    dashboard_command='
      - "--api.dashboard=true"'
    dashboard_port="
      - \"${XCIND_PROXY_DASHBOARD_PORT:-8080}:8080\""
  fi

  cat >"$XCIND_PROXY_COMPOSE" <<EOF
name: xcind-proxy

services:
  traefik:
    image: ${XCIND_PROXY_IMAGE:-traefik:v3}
    command:
      - "--configFile=/etc/traefik/traefik.yaml"${dashboard_command}
    ports:
      - "${XCIND_PROXY_HTTP_PORT:-80}:80"${dashboard_port}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
    networks:
      - xcind-proxy
    restart: unless-stopped
    labels:
      - "xcind.managed=true"
      - "xcind.component=proxy"

networks:
  xcind-proxy:
    external: true
EOF

  # Write traefik.yaml (always regenerated)
  local dashboard_config=""
  if [ "${XCIND_PROXY_DASHBOARD:-false}" = "true" ]; then
    dashboard_config="
api:
  dashboard: true
  insecure: true"
  fi

  cat >"$XCIND_PROXY_STATE_DIR/traefik.yaml" <<EOF
entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false
    network: xcind-proxy

log:
  level: INFO${dashboard_config}
EOF

  # Migration: remove generated files from old location (config dir)
  rm -f "$XCIND_PROXY_CONFIG_DIR/docker-compose.yaml" "$XCIND_PROXY_CONFIG_DIR/traefik.yaml"

  # Create Docker network if it doesn't exist
  __xcind-proxy-ensure-network
}

# Ensure the proxy is fully operational: initialized, network exists, Traefik running.
# Skips auto-start if XCIND_PROXY_AUTO_START=0.
# All output goes to stderr to avoid interfering with hook stdout.
__xcind-proxy-ensure-running() {
  # Opt-out: skip auto-start entirely
  if [[ ${XCIND_PROXY_AUTO_START:-1} == "0" ]]; then
    # Still ensure network exists for compose overlay compatibility
    __xcind-proxy-ensure-network 2>/dev/null || true
    return 0
  fi

  # Fast path: check if proxy is already running
  local running
  running=$(docker ps --filter label=xcind.component=proxy --filter status=running -q 2>/dev/null) || true
  if [ -n "$running" ]; then
    # Warn if config.sh is newer than generated files (stale)
    if [[ -f "$XCIND_PROXY_CONFIG_DIR/config.sh" && -f $XCIND_PROXY_COMPOSE ]] &&
      [[ "$XCIND_PROXY_CONFIG_DIR/config.sh" -nt $XCIND_PROXY_COMPOSE ]]; then
      echo "xcind-proxy: config.sh changed; run 'xcind-proxy up' to apply." >&2
    fi
    return 0
  fi

  # Ensure init has been done
  if [ ! -f "$XCIND_PROXY_COMPOSE" ]; then
    echo "xcind-proxy: Initializing proxy config at $XCIND_PROXY_CONFIG_DIR" >&2
  fi
  __xcind-proxy-ensure-init

  # Start Traefik
  echo "xcind-proxy: Starting Traefik proxy..." >&2
  if ! docker compose -f "$XCIND_PROXY_COMPOSE" up -d 1>&2; then
    echo "xcind-proxy: Failed to start Traefik. Check 'xcind-proxy status' for details." >&2
    echo "xcind-proxy: Port ${XCIND_PROXY_HTTP_PORT:-80} may already be in use." >&2
    # Non-fatal: the compose overlay is still generated with correct labels
  fi
}

# --------------------------------------------------------------------------
# YAML Templates
# --------------------------------------------------------------------------

# Per-service YAML snippet template
# Context labels (xcind.app.*, xcind.workspace.*) are now handled by
# dedicated hooks (xcind-app-hook, xcind-workspace-hook).
# shellcheck disable=SC2016 # Template placeholders, not shell expansions
XCIND_PROXY_SERVICE_TEMPLATE='  {compose_service}:
    networks:
      default: {}
      xcind-proxy: {}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=xcind-proxy"
      - "traefik.http.routers.{router}.rule=Host(`{hostname}`)"
      - "traefik.http.routers.{router}.entrypoints=web"
      - "traefik.http.routers.{router}.service={router}"
      - "traefik.http.services.{router}.loadbalancer.server.port={port}"
      - "xcind.export.{export}.host={hostname}"
      - "xcind.export.{export}.url=http://{hostname}"'

# Labels-only template for additional exports on the same compose service
# shellcheck disable=SC2016
XCIND_PROXY_LABELS_TEMPLATE='      - "traefik.http.routers.{router}.rule=Host(`{hostname}`)"
      - "traefik.http.routers.{router}.entrypoints=web"
      - "traefik.http.routers.{router}.service={router}"
      - "traefik.http.services.{router}.loadbalancer.server.port={port}"
      - "xcind.export.{export}.host={hostname}"
      - "xcind.export.{export}.url=http://{hostname}"'

# Per-service YAML snippet template with apex URL
# shellcheck disable=SC2016
XCIND_PROXY_SERVICE_TEMPLATE_APEX='  {compose_service}:
    networks:
      default: {}
      xcind-proxy: {}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=xcind-proxy"
      - "traefik.http.routers.{router}.rule=Host(`{hostname}`)"
      - "traefik.http.routers.{router}.entrypoints=web"
      - "traefik.http.routers.{router}.service={router}"
      - "traefik.http.services.{router}.loadbalancer.server.port={port}"
      - "traefik.http.routers.{apex_router}.rule=Host(`{apex_hostname}`)"
      - "traefik.http.routers.{apex_router}.entrypoints=web"
      - "traefik.http.routers.{apex_router}.service={apex_router}"
      - "traefik.http.services.{apex_router}.loadbalancer.server.port={port}"
      - "xcind.export.{export}.host={hostname}"
      - "xcind.export.{export}.url=http://{hostname}"
      - "xcind.apex.host={apex_hostname}"
      - "xcind.apex.url=http://{apex_hostname}"'

# --------------------------------------------------------------------------
# Export Entry Parsing
# --------------------------------------------------------------------------

# Parse a single XCIND_PROXY_EXPORTS entry into its components.
# Format: export_name[=compose_service][:port]
#
# Sets: _export_name, _compose_service, _port (empty if not specified)
__xcind-proxy-parse-entry() {
  local entry="$1"
  local right

  # Split on = (export_name=compose_service_and_port or just export_and_port)
  if [[ $entry == *=* ]]; then
    _export_name="${entry%%=*}"
    right="${entry#*=}"
  else
    right="$entry"
    _export_name=""
  fi

  # Split right side on : (service:port or just service)
  if [[ $right == *:* ]]; then
    local svc_part="${right%%:*}"
    _port="${right#*:}"
  else
    local svc_part="$right"
    _port=""
  fi

  _compose_service="$svc_part"

  # If no = was present, export name = compose service name
  if [ -z "$_export_name" ]; then
    _export_name="$_compose_service"
  fi
}

# --------------------------------------------------------------------------
# Port Inference
# --------------------------------------------------------------------------

# Infer the container port for a compose service from resolved-config.yaml.
# Requires yq.
#
# Usage:
#   port=$(__xcind-proxy-infer-port "web" /path/to/resolved-config.yaml)
__xcind-proxy-infer-port() {
  local service="$1"
  local resolved_config="$2"

  local port_count
  port_count=$(yq ".services.\"$service\".ports | length" "$resolved_config" 2>/dev/null) || port_count=0

  if [ "$port_count" -eq 0 ]; then
    echo "Error: Service '$service' has no port mappings. Specify port explicitly." >&2
    return 1
  elif [ "$port_count" -gt 1 ]; then
    echo "Error: Service '$service' has multiple port mappings. Specify port explicitly." >&2
    return 1
  fi

  # Extract the target (container) port from the single port mapping
  local target
  target=$(yq ".services.\"$service\".ports[0].target" "$resolved_config" 2>/dev/null)

  if [ -z "$target" ] || [ "$target" = "null" ]; then
    # Try published format (string like "80:8080")
    local port_str
    port_str=$(yq ".services.\"$service\".ports[0]" "$resolved_config" 2>/dev/null)
    if [[ $port_str == *:* ]]; then
      target="${port_str##*:}"
    else
      target="$port_str"
    fi
  fi

  echo "$target"
}

# --------------------------------------------------------------------------
# Service Validation
# --------------------------------------------------------------------------

# Check that a compose service exists in resolved-config.yaml.
__xcind-proxy-validate-service() {
  local service="$1"
  local resolved_config="$2"

  local exists
  exists=$(yq ".services | has(\"$service\")" "$resolved_config" 2>/dev/null)

  if [ "$exists" != "true" ]; then
    local available
    available=$(__xcind-list-services "$resolved_config" | tr '\n' ', ' | sed 's/,$//')
    echo "Error: Service '$service' not found in compose config. Available services: $available" >&2
    return 1
  fi
}

# --------------------------------------------------------------------------
# Hook Function
# --------------------------------------------------------------------------

# Main hook function called by the xcind pipeline on cache miss.
# Reads pipeline env vars and generates compose.proxy.yaml.
xcind-proxy-hook() {
  local app_root="$1"

  # Check if exports are defined (guard against unset under set -u)
  if [[ -z ${XCIND_PROXY_EXPORTS+set} || ${#XCIND_PROXY_EXPORTS[@]} -eq 0 ]]; then
    return 0
  fi

  # Default domain and source global config
  XCIND_PROXY_DOMAIN="${XCIND_PROXY_DOMAIN:-localhost}"
  local global_config="${XCIND_PROXY_CONFIG_DIR}/config.sh"
  if [ -f "$global_config" ]; then
    # shellcheck disable=SC1090
    source "$global_config"
  fi

  # Require yq
  if ! command -v yq &>/dev/null; then
    echo "Error: yq is required for proxy hook but was not found." >&2
    return 1
  fi

  local resolved_config="$XCIND_CACHE_DIR/resolved-config.yaml"

  # Select service template (apex variant when apex URL is configured)
  local service_template="$XCIND_PROXY_SERVICE_TEMPLATE"
  local apex_service_template=""
  if [[ -n ${XCIND_APP_APEX_URL_TEMPLATE:-} ]]; then
    apex_service_template="$XCIND_PROXY_SERVICE_TEMPLATE_APEX"
  fi

  # Parse all export entries and group by compose service
  local -a export_names=()
  local -a compose_services=()
  local -a ports=()
  local -a hostnames=()
  local -a routers=()
  local apex_hostname=""
  local apex_router=""

  local entry
  for entry in "${XCIND_PROXY_EXPORTS[@]}"; do
    local _export_name _compose_service _port
    __xcind-proxy-parse-entry "$entry"

    # Validate service exists
    __xcind-proxy-validate-service "$_compose_service" "$resolved_config" || return 1

    # Resolve port
    if [ -z "$_port" ]; then
      _port=$(__xcind-proxy-infer-port "$_compose_service" "$resolved_config") || return 1
    fi

    # Generate hostname
    local hostname
    hostname=$(__xcind-render-template "$XCIND_APP_URL_TEMPLATE" \
      workspace "${XCIND_WORKSPACE:-}" app "$XCIND_APP" \
      export "$_export_name" domain "$XCIND_PROXY_DOMAIN")

    # Generate router name
    local router
    router=$(__xcind-render-template "$XCIND_ROUTER_TEMPLATE" \
      workspace "${XCIND_WORKSPACE:-}" app "$XCIND_APP" \
      export "$_export_name" protocol "http")

    # Generate apex hostname and router for primary export only
    if [[ ${#export_names[@]} -eq 0 && -n $apex_service_template ]]; then
      apex_hostname=$(__xcind-render-template "$XCIND_APP_APEX_URL_TEMPLATE" \
        workspace "${XCIND_WORKSPACE:-}" app "$XCIND_APP" \
        domain "$XCIND_PROXY_DOMAIN")
      apex_router=$(__xcind-render-template "$XCIND_APEX_ROUTER_TEMPLATE" \
        workspace "${XCIND_WORKSPACE:-}" app "$XCIND_APP" \
        protocol "http")
    fi

    export_names+=("$_export_name")
    compose_services+=("$_compose_service")
    ports+=("$_port")
    hostnames+=("$hostname")
    routers+=("$router")
  done

  # Build output grouped by compose service
  local output="services:"
  local -a seen_services=()

  local i=0
  while [ "$i" -lt "${#export_names[@]}" ]; do
    local svc="${compose_services[$i]}"

    # Check if we already rendered this compose service
    local already_seen=false
    local s
    for s in "${seen_services[@]+"${seen_services[@]}"}"; do
      if [ "$s" = "$svc" ]; then
        already_seen=true
        break
      fi
    done

    if [ "$already_seen" = true ]; then
      i=$((i + 1))
      continue
    fi

    seen_services+=("$svc")

    # Find all exports for this compose service
    local first=true
    local service_block=""
    local j=0
    while [ "$j" -lt "${#export_names[@]}" ]; do
      if [ "${compose_services[$j]}" = "$svc" ]; then
        if [ "$first" = true ]; then
          # Use apex template for primary export (index 0), base template otherwise
          local effective_template="$service_template"
          if [[ $j -eq 0 && -n $apex_service_template ]]; then
            effective_template="$apex_service_template"
          fi
          # Render full service block for first export
          service_block=$(__xcind-render-template "$effective_template" \
            compose_service "$svc" \
            router "${routers[$j]}" \
            hostname "${hostnames[$j]}" \
            port "${ports[$j]}" \
            app "$XCIND_APP" \
            app_path "$app_root" \
            workspace "${XCIND_WORKSPACE:-}" \
            workspace_path "${XCIND_WORKSPACE_ROOT:-}" \
            export "${export_names[$j]}" \
            apex_router "$apex_router" \
            apex_hostname "$apex_hostname")
          first=false
        else
          # Append additional labels for subsequent exports
          local extra_labels
          extra_labels=$(__xcind-render-template "$XCIND_PROXY_LABELS_TEMPLATE" \
            router "${routers[$j]}" \
            hostname "${hostnames[$j]}" \
            port "${ports[$j]}" \
            export "${export_names[$j]}")
          service_block+=$'\n'"$extra_labels"
        fi
      fi
      j=$((j + 1))
    done

    output+=$'\n\n'"$service_block"
    i=$((i + 1))
  done

  # Append network footer
  output+=$'\n\nnetworks:\n  xcind-proxy:\n    external: true\n'

  # Write to generated dir
  echo "$output" >"$XCIND_GENERATED_DIR/compose.proxy.yaml"

  # Print compose flag to stdout
  echo "-f $XCIND_GENERATED_DIR/compose.proxy.yaml"
}

# --------------------------------------------------------------------------
# Execute Hook
# --------------------------------------------------------------------------

# EXECUTE hook: ensure proxy is running before docker compose executes.
# Runs on every invocation (not cached). Skips if XCIND_PROXY_EXPORTS is unset.
__xcind-proxy-execute-hook() {
  # shellcheck disable=SC2034  # app_root required by hook interface
  local app_root="$1"

  if [[ -z ${XCIND_PROXY_EXPORTS+set} || ${#XCIND_PROXY_EXPORTS[@]} -eq 0 ]]; then
    return 0
  fi

  __xcind-proxy-ensure-running
}
