ARG BASHVER=latest
FROM bash:${BASHVER}

ARG XCIND_BUILD_SHORT_REV=""
ARG XCIND_BUILD_LONG_REV=""
ARG XCIND_BUILD_REF=""
ARG XCIND_BUILD_DATE=""
ARG XCIND_BUILD_DIRTY="0"

LABEL org.opencontainers.image.version="0.6.0"
LABEL org.opencontainers.image.licenses="MIT"

RUN apk add --no-cache coreutils jq yq docker-cli docker-cli-compose

COPY . /opt/xcind
RUN /opt/xcind/install.sh /usr/local

# Overwrite any build-info written by install.sh (which reads the embedded
# .git, when present) with provenance supplied by the release workflow.
# %q produces shell-safe literals so unusual characters in build-args (e.g.
# branch names with quotes, backslashes, or whitespace) survive sourcing.
# Invokes bash explicitly because %q is a bash extension and the default
# /bin/sh on Alpine is busybox ash.
RUN bash -c '{ \
    printf "%s\n" "#!/usr/bin/env bash"; \
    printf "%s\n" "# xcind-build-info.bash — Generated by Dockerfile. Do not edit."; \
    printf "\n"; \
    printf "XCIND_BUILD_SOURCE=%q\n" "docker"; \
    printf "XCIND_BUILD_SHORT_REV=%q\n" "$XCIND_BUILD_SHORT_REV"; \
    printf "XCIND_BUILD_LONG_REV=%q\n" "$XCIND_BUILD_LONG_REV"; \
    printf "XCIND_BUILD_REF=%q\n" "$XCIND_BUILD_REF"; \
    printf "XCIND_BUILD_DATE=%q\n" "$XCIND_BUILD_DATE"; \
    printf "XCIND_BUILD_DIRTY=%q\n" "$XCIND_BUILD_DIRTY"; \
  } > /usr/local/lib/xcind/xcind-build-info.bash && \
  chmod 644 /usr/local/lib/xcind/xcind-build-info.bash'

WORKDIR /workspace
ENTRYPOINT ["xcind-compose"]
