ARG BASHVER=latest
FROM bash:${BASHVER}

ARG XCIND_BUILD_SHORT_REV=""
ARG XCIND_BUILD_LONG_REV=""
ARG XCIND_BUILD_REF=""
ARG XCIND_BUILD_DATE=""
ARG XCIND_BUILD_DIRTY="0"

LABEL org.opencontainers.image.version="0.5.0"
LABEL org.opencontainers.image.licenses="MIT"

RUN apk add --no-cache coreutils jq yq docker-cli docker-cli-compose

COPY . /opt/xcind
RUN /opt/xcind/install.sh /usr/local

# Overwrite any build-info written by install.sh (which reads the embedded
# .git, when present) with provenance supplied by the release workflow.
RUN printf '%s\n' \
  '#!/usr/bin/env bash' \
  '# xcind-build-info.bash — Generated by Dockerfile. Do not edit.' \
  '' \
  'XCIND_BUILD_SOURCE="docker"' \
  "XCIND_BUILD_SHORT_REV=\"$XCIND_BUILD_SHORT_REV\"" \
  "XCIND_BUILD_LONG_REV=\"$XCIND_BUILD_LONG_REV\"" \
  "XCIND_BUILD_REF=\"$XCIND_BUILD_REF\"" \
  "XCIND_BUILD_DATE=\"$XCIND_BUILD_DATE\"" \
  "XCIND_BUILD_DIRTY=\"$XCIND_BUILD_DIRTY\"" \
  >/usr/local/lib/xcind/xcind-build-info.bash \
  && chmod 644 /usr/local/lib/xcind/xcind-build-info.bash

WORKDIR /workspace
ENTRYPOINT ["xcind-compose"]
