#!/usr/bin/env bash
# install.sh — Install xcind to a PREFIX directory
set -euo pipefail

XCIND_ROOT="${0%/*}"
PREFIX="${1:-/usr/local}"

echo "Installing xcind to $PREFIX ..."

install -d "$PREFIX/bin"
install -d "$PREFIX/lib/xcind"

install -m 755 "$XCIND_ROOT/bin/xcind-application" "$PREFIX/bin/xcind-application"
install -m 755 "$XCIND_ROOT/bin/xcind-compose" "$PREFIX/bin/xcind-compose"
install -m 755 "$XCIND_ROOT/bin/xcind-config" "$PREFIX/bin/xcind-config"
install -m 755 "$XCIND_ROOT/bin/xcind-proxy" "$PREFIX/bin/xcind-proxy"
install -m 755 "$XCIND_ROOT/bin/xcind-workspace" "$PREFIX/bin/xcind-workspace"

# xcind-app alias — short form mirroring Scind's `scind app …`. Recreate on
# every install so the link always points at the current xcind-application.
ln -sf "xcind-application" "$PREFIX/bin/xcind-app"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-bootstrap.bash" "$PREFIX/lib/xcind/xcind-bootstrap.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-lib.bash" "$PREFIX/lib/xcind/xcind-lib.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-naming-lib.bash" "$PREFIX/lib/xcind/xcind-naming-lib.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-app-lib.bash" "$PREFIX/lib/xcind/xcind-app-lib.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-assigned-lib.bash" "$PREFIX/lib/xcind/xcind-assigned-lib.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-proxy-lib.bash" "$PREFIX/lib/xcind/xcind-proxy-lib.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-registry-lib.bash" "$PREFIX/lib/xcind/xcind-registry-lib.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-workspace-lib.bash" "$PREFIX/lib/xcind/xcind-workspace-lib.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-app-env-lib.bash" "$PREFIX/lib/xcind/xcind-app-env-lib.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-host-gateway-lib.bash" "$PREFIX/lib/xcind/xcind-host-gateway-lib.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-completion-bash.bash" "$PREFIX/lib/xcind/xcind-completion-bash.bash"
install -m 644 "$XCIND_ROOT/lib/xcind/xcind-completion-zsh.bash" "$PREFIX/lib/xcind/xcind-completion-zsh.bash"

# Build provenance: emit xcind-build-info.bash when installing from a git
# checkout. Tarballs without a .git directory get a plain XCIND_VERSION.
_xcind_write_build_info() {
  command -v git >/dev/null 2>&1 || return 0
  git -C "$XCIND_ROOT" rev-parse --git-dir >/dev/null 2>&1 || return 0

  local short_rev long_rev ref date dirty
  short_rev=$(git -C "$XCIND_ROOT" rev-parse --short=7 HEAD 2>/dev/null || echo "")
  long_rev=$(git -C "$XCIND_ROOT" rev-parse HEAD 2>/dev/null || echo "")
  ref=$(git -C "$XCIND_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
  [ "$ref" = "HEAD" ] && ref=""
  date=$(git -C "$XCIND_ROOT" log -1 --format=%cI HEAD 2>/dev/null || echo "")

  if git -C "$XCIND_ROOT" diff --quiet HEAD -- 2>/dev/null &&
    git -C "$XCIND_ROOT" diff --cached --quiet HEAD -- 2>/dev/null; then
    dirty="0"
  else
    dirty="1"
  fi

  cat >"$PREFIX/lib/xcind/xcind-build-info.bash" <<EOF
#!/usr/bin/env bash
# xcind-build-info.bash — Generated by install.sh. Do not edit.

XCIND_BUILD_SOURCE="install"
XCIND_BUILD_SHORT_REV="$short_rev"
XCIND_BUILD_LONG_REV="$long_rev"
XCIND_BUILD_REF="$ref"
XCIND_BUILD_DATE="$date"
XCIND_BUILD_DIRTY="$dirty"
EOF
  chmod 644 "$PREFIX/lib/xcind/xcind-build-info.bash"
}

_xcind_write_build_info

echo "Done."
echo ""
"$PREFIX/bin/xcind-config" --check || true
