name: Release npm

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642195f882660b323c62554 # v4.4.0
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
      - name: Publish to npmjs
        run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  github-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642195f882660b323c62554 # v4.4.0
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com
      - name: Scope package for GitHub Packages
        run: npm init -y --scope ${{ github.repository_owner }}
      - name: Publish to GitHub Packages
        run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
